+#toc: @li II — The Voice li@
+#bibliography: @li John Berger. _Ways of Seeing_. Penguin, 1972. li@

#chapter_two
@h2 II — The Voice h2@
He had not spoken aloud in so long that his own voice surprised him.
chapter_two#
