// Emit parts/config.wit — a Wit data-def carrying deploy config into the
// landing page, which is built through the CLI (and so can't read env itself).
//
// The landing parts reference `@site.repo` etc.; this file is generated (and
// gitignored) so the built page always points at the configured repo/brand.
//
//   node gen-config.mjs

import { writeFileSync } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { config } from './site.config.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, 'parts', 'config.wit');

// Values are single-line record fields; commas would split a record field, so
// keep them out of taglines. (Periods/slashes are fine.)
const clean = (s) => String(s).replace(/,/g, ';').replace(/\r?\n/g, ' ').trim();

// Wit interpolates data refs in body text but NOT inside param values (href),
// so the repo URL is baked as a literal into these anchor node defs. The parts
// call @gh_link / @gh_btn with just the link label (a capture, which does
// interpolate in the body). Change the URL in .env, not here.
const repo = clean(config.repo);

const wit = `~ GENERATED by gen-config.mjs from website/.env — do not edit by hand.
~ Carries deploy config into the landing page. Regenerate with \`make config\`.

#site: {
  repo - ${repo}
  title - ${clean(config.title)}
  tagline - ${clean(config.tagline)}
  url - ${clean(config.siteUrl)}
}

~ Repo links with the URL baked in (params can't interpolate data refs).
#gh_link ||label||
@a |href ${repo}| ::label:: a@
gh_link#

#gh_btn ||label||
@a |class btn btn-ghost| |href ${repo}| ::label:: a@
gh_btn#
`;

writeFileSync(OUT, wit, 'utf8');
console.log(`wrote parts/config.wit  (repo ${config.repo})`);
